apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/
  - ./ns

namespace: lco-education-platform

secretGenerator:
  - behavior: merge
    envs:
    - ./secrets.env
    name: env
    type: Opaque

configMapGenerator:
  - behavior: merge
    envs:
      - ./settings.env
    name: env
