# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/deployment-apps-v1.json

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
    spec:
      securityContext:
        fsGroup: 1000

      volumes:
        - name: dist
          emptyDir:
            sizeLimit: 256Mi

      initContainers:
        - name: build-files
          image: lco-education-platform
          command:
            - npm run build

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true

          envFrom:
            - secretRef:
                name: env
                optional: false

          resources:
            requests:
              cpu: 50m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 16Mi

          volumeMounts:
            - name: dist
              mountPath: /app/dist

      containers:
        - name: default
          image: ghcr.io/static-web-server/static-web-server:2
          command:
            - /static-web-server
            - --root=/app/dist
            - --health
            - --port=8080
            - --host=0.0.0.0

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true

          volumeMounts:
            - name: dist
              mountPath: /app/dist

          ports:
            - name: frontend
              containerPort: 8080
              protocol: TCP

          envFrom:
            - secretRef:
                name: env
                optional: false
