# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /example
  # Name will be used as the value for the `app.kubernetes.io/component`
  # selector label and updated automatically by `kpt fn render`.
  # So no need to set those manually.
  name: proxy-jpl
  labels:
    app.kubernetes.io/component: proxy-jpl
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|default|example'
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: proxy-jpl
  template:
    metadata:
      labels:
        app.kubernetes.io/component: proxy-jpl
    spec:
      volumes:
        - name: config
          configMap:
            name: proxy-jpl-haproxy
            optional: false
      containers:
        - name: default
          image: "haproxy:3.2-alpine"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/haproxy/haproxy.cfg
              subPath: haproxy.cfg
            - name: config
              mountPath: /usr/local/etc/haproxy/cors.lua
              subPath: cors.lua
