apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata: # kpt-merge: /svc-example
  name: svc-example
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'fn.kpt.dev|ApplyReplacements|default|svc-example'
replacements:
  - source:
      kind: Service
      fieldPath: metadata.name
    targets:
      - select:
          kind: Kustomization
        fieldPaths:
          - metadata.name
        options:
          delimiter: "svc-"
          index: 1
      - select:
          kind: ApplyReplacements
        fieldPaths:
          - metadata.name
        options:
          delimiter: "svc-"
          index: 1
  - source:
      kind: Service
      fieldPath: spec.selector.[app.kubernetes.io/component]
    targets:
      - select:
          kind: Service
        fieldPaths:
          - metadata.labels.[app.kubernetes.io/component]
        options:
          create: true
