apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./deploy-frontend
  - ./svc-frontend

labels:
  - pairs:
      app.kubernetes.io/name: lco-education-platform
    includeSelectors: true

secretGenerator: 
  - name: env
  - type: Opaque
