apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./deploy-frontend
  - ./svc-frontend

labels:
  - pairs:
      app.kubernetes.io/name: lco-education-platform
    includeSelectors: true

configMapGenerator:
  - name: app-config
    files:
     - config.json

secretGenerator:
 - name: env
   envs:
    - ./secrets.env
   type: Opaque
