apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./deploy-frontend
  - ./svc-frontend
  - ./deploy-proxy-jpl/
  - ./svc-proxy-jpl/

labels:
  - pairs:
      app.kubernetes.io/name: lco-education-platform
    includeSelectors: true

configMapGenerator:
  - name: app-config
    files:
     - config.json

  - name: proxy-jpl-haproxy
    files:
      - haproxy.cfg=./proxy-jpl-haproxy.cfg
      - cors.lua=./proxy-jpl-cors.lua
